// Generated by scripts/generate-font-manifest.mjs after updating Noto Sans SC.
// Literal file paths prevent the server tracer from including unused formats and weights.
import "server-only";
import { join } from "node:path";
import { fontData } from "./image-fonts";

export const nicknameFonts: Record<string, () => Promise<Buffer[]>> = {
  "4": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-4-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-4-700-normal.woff")),
  ]),
  "5": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-5-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-5-700-normal.woff")),
  ]),
  "6": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-6-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-6-700-normal.woff")),
  ]),
  "21": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-21-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-21-700-normal.woff")),
  ]),
  "22": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-22-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-22-700-normal.woff")),
  ]),
  "23": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-23-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-23-700-normal.woff")),
  ]),
  "24": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-24-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-24-700-normal.woff")),
  ]),
  "25": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-25-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-25-700-normal.woff")),
  ]),
  "26": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-26-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-26-700-normal.woff")),
  ]),
  "27": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-27-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-27-700-normal.woff")),
  ]),
  "28": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-28-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-28-700-normal.woff")),
  ]),
  "29": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-29-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-29-700-normal.woff")),
  ]),
  "30": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-30-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-30-700-normal.woff")),
  ]),
  "31": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-31-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-31-700-normal.woff")),
  ]),
  "32": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-32-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-32-700-normal.woff")),
  ]),
  "33": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-33-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-33-700-normal.woff")),
  ]),
  "34": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-34-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-34-700-normal.woff")),
  ]),
  "35": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-35-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-35-700-normal.woff")),
  ]),
  "36": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-36-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-36-700-normal.woff")),
  ]),
  "37": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-37-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-37-700-normal.woff")),
  ]),
  "38": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-38-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-38-700-normal.woff")),
  ]),
  "39": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-39-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-39-700-normal.woff")),
  ]),
  "40": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-40-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-40-700-normal.woff")),
  ]),
  "41": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-41-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-41-700-normal.woff")),
  ]),
  "42": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-42-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-42-700-normal.woff")),
  ]),
  "43": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-43-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-43-700-normal.woff")),
  ]),
  "44": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-44-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-44-700-normal.woff")),
  ]),
  "45": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-45-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-45-700-normal.woff")),
  ]),
  "46": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-46-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-46-700-normal.woff")),
  ]),
  "47": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-47-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-47-700-normal.woff")),
  ]),
  "48": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-48-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-48-700-normal.woff")),
  ]),
  "49": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-49-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-49-700-normal.woff")),
  ]),
  "50": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-50-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-50-700-normal.woff")),
  ]),
  "51": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-51-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-51-700-normal.woff")),
  ]),
  "52": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-52-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-52-700-normal.woff")),
  ]),
  "53": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-53-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-53-700-normal.woff")),
  ]),
  "54": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-54-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-54-700-normal.woff")),
  ]),
  "55": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-55-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-55-700-normal.woff")),
  ]),
  "56": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-56-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-56-700-normal.woff")),
  ]),
  "57": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-57-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-57-700-normal.woff")),
  ]),
  "58": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-58-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-58-700-normal.woff")),
  ]),
  "59": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-59-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-59-700-normal.woff")),
  ]),
  "60": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-60-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-60-700-normal.woff")),
  ]),
  "61": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-61-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-61-700-normal.woff")),
  ]),
  "62": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-62-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-62-700-normal.woff")),
  ]),
  "63": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-63-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-63-700-normal.woff")),
  ]),
  "64": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-64-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-64-700-normal.woff")),
  ]),
  "65": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-65-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-65-700-normal.woff")),
  ]),
  "66": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-66-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-66-700-normal.woff")),
  ]),
  "67": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-67-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-67-700-normal.woff")),
  ]),
  "68": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-68-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-68-700-normal.woff")),
  ]),
  "69": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-69-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-69-700-normal.woff")),
  ]),
  "70": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-70-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-70-700-normal.woff")),
  ]),
  "71": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-71-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-71-700-normal.woff")),
  ]),
  "72": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-72-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-72-700-normal.woff")),
  ]),
  "73": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-73-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-73-700-normal.woff")),
  ]),
  "74": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-74-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-74-700-normal.woff")),
  ]),
  "75": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-75-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-75-700-normal.woff")),
  ]),
  "76": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-76-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-76-700-normal.woff")),
  ]),
  "77": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-77-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-77-700-normal.woff")),
  ]),
  "78": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-78-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-78-700-normal.woff")),
  ]),
  "79": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-79-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-79-700-normal.woff")),
  ]),
  "80": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-80-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-80-700-normal.woff")),
  ]),
  "81": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-81-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-81-700-normal.woff")),
  ]),
  "82": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-82-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-82-700-normal.woff")),
  ]),
  "83": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-83-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-83-700-normal.woff")),
  ]),
  "84": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-84-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-84-700-normal.woff")),
  ]),
  "85": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-85-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-85-700-normal.woff")),
  ]),
  "86": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-86-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-86-700-normal.woff")),
  ]),
  "87": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-87-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-87-700-normal.woff")),
  ]),
  "88": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-88-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-88-700-normal.woff")),
  ]),
  "89": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-89-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-89-700-normal.woff")),
  ]),
  "90": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-90-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-90-700-normal.woff")),
  ]),
  "91": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-91-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-91-700-normal.woff")),
  ]),
  "97": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-97-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-97-700-normal.woff")),
  ]),
  "98": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-98-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-98-700-normal.woff")),
  ]),
  "99": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-99-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-99-700-normal.woff")),
  ]),
  "100": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-100-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-100-700-normal.woff")),
  ]),
  "101": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-101-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-101-700-normal.woff")),
  ]),
  "102": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-102-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-102-700-normal.woff")),
  ]),
  "103": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-103-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-103-700-normal.woff")),
  ]),
  "104": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-104-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-104-700-normal.woff")),
  ]),
  "105": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-105-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-105-700-normal.woff")),
  ]),
  "106": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-106-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-106-700-normal.woff")),
  ]),
  "107": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-107-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-107-700-normal.woff")),
  ]),
  "108": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-108-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-108-700-normal.woff")),
  ]),
  "109": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-109-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-109-700-normal.woff")),
  ]),
  "110": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-110-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-110-700-normal.woff")),
  ]),
  "111": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-111-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-111-700-normal.woff")),
  ]),
  "112": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-112-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-112-700-normal.woff")),
  ]),
  "113": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-113-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-113-700-normal.woff")),
  ]),
  "114": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-114-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-114-700-normal.woff")),
  ]),
  "115": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-115-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-115-700-normal.woff")),
  ]),
  "116": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-116-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-116-700-normal.woff")),
  ]),
  "117": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-117-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-117-700-normal.woff")),
  ]),
  "118": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-118-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-118-700-normal.woff")),
  ]),
  "119": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-119-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-119-700-normal.woff")),
  ]),
  "cyrillic": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-cyrillic-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-cyrillic-700-normal.woff")),
  ]),
  "vietnamese": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-vietnamese-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-vietnamese-700-normal.woff")),
  ]),
  "latin-ext": () => Promise.all([
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-latin-ext-400-normal.woff")),
    fontData(join(process.cwd(), "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-latin-ext-700-normal.woff")),
  ]),
};
